language: c
sudo: required
services:
    - docker

stages:
    - compile
    - test

jobs:
    include:
        - stage: compile
          script:
            - docker image build build-images -t webcom-sdk-c
            - docker container run --workdir /tmp/webcom-sdk-c/build --detach -v "$(pwd):/tmp/webcom-sdk-c/" webcom-sdk-c sleep 10000 > .container_id
            - docker container exec $(cat .container_id) cmake .. -DBUILD_HTML_DOCUMENTATION=ON
            - docker container exec $(cat .container_id) make

        - stage: test
          script:
            - docker image build build-images -t webcom-sdk-c
            - docker container run --workdir /tmp/webcom-sdk-c/build --detach -v "$(pwd):/tmp/webcom-sdk-c/" webcom-sdk-c sleep 10000 > .container_id
            - docker container exec $(cat .container_id) cmake ..
            - docker container exec $(cat .container_id) make
            - docker container exec $(cat .container_id) make test
