language: c
sudo: required
services:
    - docker

stages:
    - compile
    - test
    - name: deploy_doc
      if: branch = master
    - package

jobs:
    include:
        - stage: compile
          script:
            - docker image build -f build-images/Dockerfile.alpine build-images -t webcom-sdk-c-build
            - docker container run --workdir /tmp/webcom-sdk-c/build --detach -v "$(pwd):/tmp/webcom-sdk-c/" webcom-sdk-c-build sleep 1000 > .container_id
            - docker container exec $(cat .container_id) cmake ..
            - docker container exec $(cat .container_id) make

        - stage: test
          script:
            - docker image build -f build-images/Dockerfile.alpine build-images -t webcom-sdk-c-build
            - docker container run --workdir /tmp/webcom-sdk-c/build --detach -v "$(pwd):/tmp/webcom-sdk-c/" webcom-sdk-c-build sleep 1000 > .container_id
            - docker container exec $(cat .container_id) cmake ..
            - docker container exec $(cat .container_id) make
            - docker container exec $(cat .container_id) make test

        - stage: deploy_doc
          script:
            - docker image build -f build-images/Dockerfile.alpine.build-doc build-images -t webcom-sdk-c-build-doc
            - docker container run --workdir /tmp/webcom-sdk-c/build --detach -v "$(pwd):/tmp/webcom-sdk-c/" webcom-sdk-c-build-doc sleep 1000 > .container_id
            - docker container exec $(cat .container_id) cmake ../doc -DBUILD_HTML_DOCUMENTATION=ON -DBUILD_MAN_PAGES=OFF
            - docker container exec $(cat .container_id) make doc
          deploy:
            provider: pages
            skip_cleanup: true
            local_dir: build/html
            github_token: $GITHUB_TOKEN

        - stage: package
          script:
            - mkdir packages
            - docker image build -f build-images/Dockerfile.ubuntu16.04.build-deb build-images -t webcom-sdk-c-package-ubuntu16.04
            - mkdir build-ubuntu16.04
            - docker container run --workdir /tmp/webcom-sdk-c/build-ubuntu16.04 --detach -v "$(pwd):/tmp/webcom-sdk-c/" webcom-sdk-c-package-ubuntu16.04 sleep 1000 > .container_id
            - docker container exec $(cat .container_id) cmake .. -DPACKAGE_FLAVOUR=ubuntu16.04 -DCPACK_OUTPUT_FILE_PREFIX=/tmp/webcom-sdk-c/packages
            - docker container exec $(cat .container_id) make
            - docker container exec $(cat .container_id) make test
            - docker container exec $(cat .container_id) make package
